# Generated by Django 5.0.6 on 2024-06-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='capital',
            field=models.CharField(default='baghdad', max_length=255),
        ),
    ]
