# Generated by Django 4.2.4 on 2024-06-13 08:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_promotion_discount_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='products',
        ),
        migrations.AddField(
            model_name='package',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.package')),
                ('products', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
