# Generated by Django 4.2.4 on 2023-08-08 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_author_options_alter_publisher_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='description',
            new_name='descriptions',
        ),
        migrations.AlterField(
            model_name='product',
            name='auther',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.author'),
        ),
    ]
