# Generated by Django 4.2.4 on 2024-06-13 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_package_products_package_descriptions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packageitem',
            old_name='products',
            new_name='product',
        ),
    ]
