# Generated by Django 4.2.4 on 2023-08-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_description_publisher_descriptions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.AddField(
            model_name='promotion',
            name='titlle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
