# Generated by Django 4.2.4 on 2024-06-13 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_products_packageitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='media/store/images'),
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/store/package_images')),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='store.package')),
            ],
        ),
    ]
