# Generated by Django 5.0.6 on 2024-06-19 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prom', to='store.promotion'),
        ),
    ]
