# Generated by Django 4.2.4 on 2023-08-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_author_options_promotion_titlle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='titlle',
            field=models.CharField(max_length=255),
        ),
    ]
