# Generated by Django 5.0.6 on 2024-06-19 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='store.promotion'),
        ),
    ]
