# Generated by Django 4.2.4 on 2023-08-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_promotion_titlle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='titlle',
            new_name='title',
        ),
    ]
