# Generated by Django 4.2.4 on 2024-06-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_packageimage_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(null=True, upload_to='store/package_image'),
        ),
        migrations.DeleteModel(
            name='PackageImage',
        ),
    ]
