# Generated by Django 4.2.4 on 2024-06-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likeditem',
            options={},
        ),
        migrations.RenameField(
            model_name='likeditem',
            old_name='productLiked',
            new_name='product',
        ),
    ]
